name: Release releases

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2.2.0
      with:
        go-version: '^1.17.0'
    - uses: actions/checkout@v2
    
    - name: Build
      run: make
    - name: Release
      uses: softprops/action-gh-release@v1
        files: 'build/*'

