name: Release releases

on:
  push:
    branches:
    - 'release/v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2.2.0
    - uses: actions/checkout@v2
    
    - name: Build
      run: make
